name = "athletetime"
compatibility_date = "2024-09-21"
pages_build_output_dir = "dist"

# D1 데이터베이스 설정
[[d1_databases]]
binding = "DB"
database_name = "athletetime-production"
database_id = "your-database-id-here"

# KV 네임스페이스 (선택사항)
[[kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"

# 환경 변수
[vars]
NODE_ENV = "production"